### ISSUE TITLE
Provide information why this is a binary, not a library

### ISSUE THREAD

**Issue by mkaput** [software-mansion/universal-sierra-compiler#15]
I think many people will ponder this question:

> Why is this a binary and not a regular Rust crate?

Especially as for some projects, it would be much easier to consume a Rust crate. I think I get why it is this like this, but it's completely not an obvious answer. I think the README is a fine place.

**Comment by Mirko-von-Leipzig** [comment]
That might be good because I don't understand why its not a crate in addition to the binary for cli use.
